name: Continuous Deployment Live

on:
  # push:
  #   branches:
  #     - master
  #     - main
  workflow_dispatch:
    branches:
      - master
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SSH Create web API folder
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{ secrets.REMOTE_TARGET_HOME }}
            rm -rf ./api
            mkdir -p ./api
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
      - name: SSH transfer API in server folder
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET_HOME }}/api
      - name: SSH Copy API to web folder & create Uploads folder & Install dependencies
        uses: fifsky/ssh-action@master
        with:
          command: |
            mkdir -p ${{ secrets.REMOTE_TARGET_WWW }}/api/
            cd ${{ secrets.REMOTE_TARGET_WWW }}/api/
            php7.4 artisan down
            rm -r ./database/migrations/*
            cp -r ${{ secrets.REMOTE_TARGET_HOME }}/api/* ./
            cp ${{ secrets.REMOTE_TARGET_HOME }}/.env.api ./.env
            php7.4 /usr/local/bin/composer install
            php7.4 artisan migrate
            php7.4 artisan cache:clear
            php7.4 artisan queue:restart
            php7.4 artisan up
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
